
var az_matome = [
//	['ISTP','テネシー',''],
['ISTP','アラバマ',''],
	['ISTP','ジョージア',''],
	['ISTP','モントピリア',''],
//	['ISTP','マッコール',''],
//	['ISTP','モーリー',''],
	['ISTP','ラフィー',''],
	['ISTP','ニコラス',''],
//	['ISTP','フート',''],
//	['ISTP','スモーリー',''],
//	['ISTP','ジャマイカ',''],
//	['ISTP','アカスタ',''],
//	['ISTP','ハンター',''],
//	['ISTP','長春改','長春'],
//	['ISTP','日向改','日向'],
	['ISTP','土佐',''],
//	['ISTP','榛名',''],
//	['ISTP','加賀',''],
	['ISTP','摩耶',''],
	['ISTP','夕張',''],
//	['ISTP','鬼怒',''],
//	['ISTP','三日月',''],
//	['ISTP','江風',''],
//	['ISTP','霞',''],
//	['ISTP','野分',''],
//	['ISTP','伊58',''],
	['ISTP','プリンツ・アーダルベルト','アーダルベルト'],
	['ISTP','U-110',''],
	['ISTP','ジャン・バール',''],
	['ISTP','ル・マラン',''],
	['ISTJ','コロラド',''],
//	['ISTJ','ウェストバージニア',''],
	['ISTJ','サウスダコタ',''],
	['ISTJ','エンタープライズ',''],
	['ISTJ','エセックス',''],
//	['ISTJ','カサブランカ',''],
//	['ISTJ','ノーザンプトン',''],
//	['ISTJ','ブルックリン',''],
//	['ISTJ','バーミンガム',''],
	['ISTJ','レナウン',''],
	['ISTJ','カーリュー',''],
//	['ISTJ','ブルドッグ',''],
	['ISTJ','鎮海',''],
//	['ISTJ','タリン',''],
//	['ISTJ','グロズヌイ',''],
//	['ISTJ','ベアルン',''],
//	['ISTJ','サン・ルイ',''],
//	['ISTJ','フォルバン',''],
//	['ISTJ','長門',''],
	['ISTJ','駿河',''],
	['ISTJ','蒼龍',''],
	['ISTJ','高雄',''],
//	['ISTJ','筑摩',''],
//	['ISTJ','阿武隈',''],
//	['ISTJ','三隈',''],
	['ISTJ','能代',''],
//	['ISTJ','旗風',''],
//	['ISTJ','朝潮',''],
//	['ISTJ','黒潮',''],
//	['ISTJ','宵月',''],
//	['ISTJ','ザイドリッツ',''],
//	['ISTJ','ブリュンヒルデ',''],
//	['ISTJ','ヴェーザー',''],
	['ISTJ','アドミラル・グラーフ・シュペー','シュペー'],
//	['ISTJ','ケルン',''],
//	['ISTJ','マインツ',''],
//	['ISTJ','カラビニエーレ',''],
//	['ISFP','オクラホマ',''],
//	['ISFP','カリフォルニア',''],
//	['ISFP','デューイ',''],
	['ISFP','ハムマン',''],
//	['ISFP','マラニー',''],
	['ISFP','エルドリッジ改','エルドリッジ'],
//	['ISFP','ロドニー',''],
	['ISFP','インドミタブル',''],
//	['ISFP','パーシュース',''],
	['ISFP','キュラソー',''],
//	['ISFP','サウサンプトン',''],
	['ISFP','ニューカッスル',''],
	['ISFP','シリアス',''],
//	['ISFP','アーデント',''],
//	['ISFP','クレセント',''],
	['ISFP','シグニット',''],
//	['ISFP','エコー',''],
//	['ISFP','フォックスハウンド',''],
//	['ISFP','ジュピター',''],
	['ISFP','アヴローラ',''],
//	['ISFP','ルピニャート',''],
//	['ISFP','古鷹',''],
//	['ISFP','足柄',''],
//	['ISFP','鳥海',''],
	['ISFP','伊吹',''],
//	['ISFP','長良',''],
	['ISFP','吾妻',''],
	['ISFP','樫野',''],
	['ISFP','綾波',''],
//	['ISFP','暁',''],
//	['ISFP','有明',''],
//	['ISFP','夕暮',''],
//	['ISFP','大潮',''],
//	['ISFP','満潮',''],
//	['ISFP','親潮',''],
//	['ISFP','長波',''],
//	['ISFP','春月',''],
//	['ISFP','伊19',''],
//	['ISFP','ル・マルス',''],
//	['ISFP','エマヌエーレ・ペッサーニョ','エマヌエーレ'],
//	['ISFP','ドルフィン',''],
	['ISFJ','ノースカロライナ',''],
//	['ISFJ','レキシントン',''],
	['ISFJ','シャングリラ',''],
	['ISFJ','タイコンデロガ',''],
//	['ISFJ','バターン',''],
//	['ISFJ','エールウィン',''],
//	['ISFJ','フレッチャー',''],
	['ISFJ','フッド',''],
	['ISFJ','セントー',''],
//	['ISFJ','ロンドン',''],
//	['ISFJ','ドーセットシャー',''],
//	['ISFJ','リアンダー',''],
	['ISFJ','オーロラ',''],
	['ISFJ','ハーマイオニー',''],
//	['ISFJ','フォーチュン',''],
//	['ISFJ','イカルス',''],
	['ISFJ','逸仙',''],
//	['ISFJ','フランドル',''],
//	['ISFJ','扶桑改','扶桑'],
	['ISFJ','翔鶴',''],
//	['ISFJ','鳳翔',''],
//	['ISFJ','鈴谷',''],
//	['ISFJ','荒潮',''],
	['ISFJ','花月',''],
//	['ISFJ','伊25',''],
//	['ISFJ','ニュルンベルク',''],
	['ISFJ','ダンケルク',''],
	['ISFJ','アルジェリー',''],
//	['ISFJ','ケルサン',''],
	['INTP','バンカー・ヒル',''],
	['INTP','ロング・アイランド',''],
	['INTP','インディアナポリス',''],
//	['INTP','ヴィンセンス',''],
	['INTP','ヘレナ',''],
//	['INTP','ブラック・プリンス',''],
	['INTP','平海',''],
	['INTP','天城',''],
	['INTP','神通',''],
//	['INTP','浦波',''],
//	['INTP','電',''],
	['INTP','伊13',''],
	['INTP','ティルピッツ',''],
//	['INTP','グナイゼナウ',''],
//	['INTP','リュッツォウ',''],
	['INTP','Z46',''],
	['INTP','U-47',''],
	['INTP','ガスコーニュ',''],
//	['INTP','タルテュ',''],
//	['INTP','コンテ・ディ・カブール','カブール'],
//	['INTJ','カッシン',''],
	['INTJ','プリンス・オブ・ウェールズ','ウェールズ'],
	['INTJ','モナーク',''],
	['INTJ','シェフィールド',''],
	['INTJ','エレバス',''],
	['INTJ','ソビエツカヤ・ロシア',''],
	['INTJ','タシュケント',''],
	['INTJ','不知火',''],
//	['INTJ','浜風',''],
	['INTJ','ビスマルク',''],
	['INTJ','ウルリッヒ・フォン・フッテン','ウルリッヒ'],
	['INTJ','グラーフ・ツェッペリン','ツェッペリン'],
	['INTJ','アウグスト・フォン・パーセヴァル','アウグスト'],
//	['INTJ','Z2',''],
	['INTJ','ローマ',''],
//	['INFP','ルイビル',''],
	['INFP','アンカレッジ',''],
	['INFP','ホノルル',''],
//	['INFP','ジュノー(軽巡)',''],
//	['INFP','ジェンキンス',''],
//	['INFP','スペンス',''],
//	['INFP','モリソン',''],
//	['INFP','グロリアス',''],
	['INFP','ユニコーン',''],
//	['INFP','サフォーク',''],
//	['INFP','ノーフォーク',''],
	['INFP','グラスゴー',''],
	['INFP','ダイドー',''],
//	['INFP','コメット',''],
//	['INFP','ジュノー(駆逐)',''],
	['INFP','テラー',''],
//	['INFP','太原改','太原'],
	['INFP','大鳳',''],
	['INFP','龍鳳',''],
	['INFP','隼鷹',''],
	['INFP','千歳',''],
	['INFP','五十鈴',''],
//	['INFP','最上改','最上'],
//	['INFP','綾瀬',''],
//	['INFP','如月',''],
//	['INFP','卯月',''],
//	['INFP','文月',''],
//	['INFP','初春',''],
//	['INFP','白露',''],
//	['INFP','谷風',''],
//	['INFP','清波',''],
//	['INFP','新月',''],
//	['INFP','伊56',''],
	['INFP','ライプツィヒ',''],
//	['INFP','エルビング',''],
//	['INFP','Z9',''],
//	['INFP','U-557',''],
//	['INFP','トリチェリ',''],
	['INFJ','アリゾナ',''],
	['INFJ','マサチューセッツ',''],
//	['INFJ','ヨークタウン',''],
	['INFJ','クインシー',''],
	['INFJ','スウィフトシュア',''],
	['INFJ','リシュリュー',''],
	['INFJ','リヨン',''],
	['INFJ','ジャンヌ・ダルク',''],
	['INFJ','信濃',''],
	['INFJ','ローン',''],
//	['ESTP','ネバダ',''],
//	['ESTP','メリーランド',''],
	['ESTP','ワシントン',''],
//	['ESTP','ワスプ',''],
//	['ESTP','ボーグ',''],
//	['ESTP','ペンサコーラ',''],
//	['ESTP','ミネアポリス',''],
//	['ESTP','ウィチタ',''],
//	['ESTP','マーブルヘッド',''],
//	['ESTP','フェニックス',''],
	['ESTP','クリーブランド',''],
//	['ESTP','ビロクシ',''],
//	['ESTP','ダウンズ',''],
//	['ESTP','ヘイゼルウッド',''],
	['ESTP','キング・ジョージ5世','KGV'],
	['ESTP','アーク・ロイヤル',''],
//	['ESTP','ハーミーズ',''],
//	['ESTP','エスキモー',''],
	['ESTP','アバークロンビー',''],
//	['ESTP','ガングート',''],
//	['ESTP','伊勢改','伊勢'],
	['ESTP','出雲',''],
//	['ESTP','霧島',''],
	['ESTP','白龍',''],
//	['ESTP','飛鷹',''],
//	['ESTP','川内',''],
//	['ESTP','水無月',''],
//	['ESTP','夕立改','夕立'],
	['ESTP','シャルンホルスト',''],
//	['ESTP','マクデブルク',''],
	['ESTP','Z1',''],
//	['ESTP','U-73',''],
	['ESTP','U-101',''],
//	['ESTP','U-81',''],
	['ESTP','U-96',''],
//	['ESTP','ジュリオ・チェザーレ',''],
//	['ESTP','リットリオ',''],
	['ESTP','ポーラ',''],
	['ESTJ','ペンシルベニア',''],
	['ESTJ','イントレピッド',''],
	['ESTJ','ラングレー',''],
	['ESTJ','インディペンデンス',''],
//	['ESTJ','サンフアン',''],
//	['ESTJ','キンバリー',''],
//	['ESTJ','ウォースパイト改','ウォースパイト'],
	['ESTJ','サセックス',''],
	['ESTJ','グロスター',''],
	['ESTJ','ハーディ',''],
//	['ESTJ','ジャージー',''],
	['ESTJ','寧海',''],
//	['ESTJ','海容',''],
//	['ESTJ','鞍山改','鞍山'],
	['ESTJ','紀伊',''],
//	['ESTJ','加古',''],
//	['ESTJ','妙高',''],
	['ESTJ','ペーター・シュトラッサー','シュトラッサー'],
	['ESTJ','アドミラル・ヒッパー','ヒッパー'],
//	['ESTJ','Z19',''],
//	['ESTJ','Z21',''],
	['ESTJ','Z23',''],
	['ESFP','ホーネット',''],
//	['ESFP','ソルトレイクシティ',''],
//	['ESFP','ヒューストン',''],
//	['ESFP','サンフランシスコ',''],
//	['ESFP','オマハ',''],
//	['ESFP','リッチモンド',''],
//	['ESFP','コロンビア',''],
	['ESFP','シアトル',''],
//	['ESFP','ベンソン',''],
//	['ESFP','ベイリー',''],
//	['ESFP','オーリック',''],
	['ESFP','アレン・M・サムナー','アレン'],
//	['ESFP','デイス',''],
	['ESFP','レパルス',''],
	['ESFP','ヴィクトリアス',''],
	['ESFP','フォーミダブル',''],
//	['ESFP','ケント',''],
//	['ESFP','アキリーズ',''],
	['ESFP','エディンバラ',''],
//	['ESFP','ビーグル',''],
//	['ESFP','マッチレス',''],
//	['ESFP','マスケティーア',''],
	['ESFP','エミール・ベルタン','ベルタン'],
//	['ESFP','ル・テメレール',''],
//	['ESFP','シュルクーフ',''],
//	['ESFP','山城改','山城'],
	['ESFP','葛城',''],
//	['ESFP','千代田',''],
//	['ESFP','熊野',''],
//	['ESFP','睦月',''],
	['ESFP','吹雪',''],
//	['ESFP','響',''],
//	['ESFP','若葉',''],
//	['ESFP','山風',''],
//	['ESFP','磯風',''],
//	['ESFP','伊26',''],
	['ESFP','エルベ',''],
//	['ESFP','Z18',''],
//	['ESFP','Z20',''],
	['ESFP','Z52',''],
//	['ESFP','U-1206',''],
//	['ESFP','ポーツマウス・アドベンチャー','ポーツマウス'],
	['ESFJ','ポートランド',''],
//	['ESFJ','アストリア',''],
	['ESFJ','ブレマートン',''],
//	['ESFJ','ローリー',''],
//	['ESFJ','アトランタ',''],
//	['ESFJ','グリッドレイ',''],
//	['ESFJ','クレイヴン',''],
//	['ESFJ','ラドフォード',''],
	['ESFJ','ヴェスタル',''],
	['ESFJ','エクセター',''],
	['ESFJ','ベルファスト',''],
//	['ESFJ','フィジー',''],
	['ESFJ','カリブディス',''],
	['ESFJ','ジャベリン',''],
//	['ESFJ','長風',''],
	['ESFJ','ムルマンスク',''],
	['ESFJ','三笠',''],
//	['ESFJ','比叡',''],
//	['ESFJ','赤城',''],
//	['ESFJ','衣笠',''],
//	['ESFJ','那智',''],
//	['ESFJ','松風',''],
	['ESFJ','時雨',''],
	['ESFJ','涼月',''],
//	['ESFJ','ケーニヒスベルク',''],
	['ESFJ','ザラ',''],
//	['ESFJ','アミティ',''],
	['ENTP','サラトガ',''],
//	['ENTP','シカゴ',''],
//	['ENTP','コンコード',''],
//	['ENTP','シムス',''],
//	['ENTP','ホビー',''],
//	['ENTP','バッチ',''],
//	['ENTP','スタンリー',''],
	['ENTP','イングラハム',''],
	['ENTP','アルバコア',''],
//	['ENTP','デューク・オブ・ヨーク',''],
//	['ENTP','シュロップシャー',''],
	['ENTP','ヨーク',''],
	['ENTP','チェシャー',''],
	['ENTP','エイジャックス',''],
	['ENTP','ネプチューン',''],
//	['ENTP','アマゾン',''],
//	['ENTP','伏波',''],
	['ENTP','パーミャチ・メルクーリヤ','クーちゃん'],
//	['ENTP','青葉',''],
	['ENTP','阿賀野',''],
//	['ENTP','神風',''],
//	['ENTP','長月',''],
//	['ENTP','初霜',''],
//	['ENTP','明石',''],
	['ENTP','プリンツ・オイゲン',''],
//	['ENTP','カールスルーエ',''],
	['ENTP','エムデン',''],
//	['ENTP','U-522',''],
//	['ENTP','ラ・ガリソニエール',''],
	['ENTP','トレント',''],
	['ENTJ','メンフィス',''],
//	['ENTJ','ネルソン',''],
	['ENTJ','アリシューザ',''],
	['ENTJ','武蔵',''],
	['ENTJ','金剛',''],
	['ENTJ','浦風',''],
	['ENTJ','オーディン',''],
	['ENTJ','エーギル',''],
	['ENTJ','クレマンソー',''],
	['ENTJ','ヴィットリオ・ヴェネト','ヴィットリオ'],
	['ENTJ','キズナアイ',''],
	['ENFP','ニュージャージー',''],
//	['ENFP','レンジャー',''],
	['ENFP','サンディエゴ改','サンディエゴ'],
//	['ENFP','リノ',''],
//	['ENFP','デンバー',''],
//	['ENFP','カーク',''],
//	['ENFP','サッチャー',''],
//	['ENFP','ブッシュ',''],
//	['ENFP','ハルゼー・パウエル',''],
//	['ENFP','クーパー',''],
//	['ENFP','ブルーギル',''],
//	['ENFP','カヴァラ',''],
	['ENFP','クイーン・エリザベス','QE'],
	['ENFP','ヴァリアント',''],
	['ENFP','ヴァンガード',''],
	['ENFP','ヴァンパイア',''],
//	['ENFP','グレンヴィル',''],
//	['ENFP','グローウォーム',''],
//	['ENFP','華甲',''],
//	['ENFP','撫順改','撫順'],
//	['ENFP','シュフラン',''],
//	['ENFP','陸奥',''],
//	['ENFP','飛龍',''],
	['ENFP','瑞鶴',''],
//	['ENFP','龍驤',''],
//	['ENFP','祥鳳',''],
//	['ENFP','那珂',''],
//	['ENFP','雷',''],
//	['ENFP','陽炎',''],
	['ENFP','雪風',''],
//	['ENFP','巻波',''],
//	['ENFP','北風',''],
	['ENFP','島風',''],
//	['ENFP','伊168',''],
	['ENFP','ドイッチュラント',''],
//	['ENFP','ブリュッヒャー',''],
//	['ENFP','プリンツ・ハインリヒ',''],
//	['ENFP','Z25',''],
	['ENFP','Z35',''],
//	['ENFP','Z36',''],
//	['ENFP','U-556',''],
//	['ENFP','ヴォークラン',''],
	['ENFP','ロイヤル・フォーチュン','ロイフォ'],
//	['ENFP','汎用型ブリ',''],
//	['ENFP','試作型ブリMKII',''],
	['ENFJ','サン・ジャシント',''],
	['ENFJ','ボルチモア',''],
	['ENFJ','セントルイス',''],
	['ENFJ','チャールズ・オースバーン','オースバーン'],
	['ENFJ','ハウ',''],
//	['ENFJ','イラストリアス',''],
	['ENFJ','チェイサー',''],
//	['ENFJ','ガラティア',''],
	['ENFJ','チャパエフ',''],
	['ENFJ','グロームキィ',''],
	['ENFJ','ル・トリオンファン',''],
	['ENFJ','愛宕',''],
	['ENFJ','フリードリヒ・デア・グローセ','フリードリヒ'],
	['ENFJ','Z28',''],

]
var chara_end = {
    "ESTJ":"estj",
    "INFJ":"infj",
    "ESFJ":"esfj",
    "ESFP":"esfp",
    "ENTJ":"entj",
    "ISFJ":"isfj",
    "ENFJ":"enfj",
    "INTJ":"intj",
    "ISTJ":"istj",
    "ISTP":"istp",
    "ENTP":"entp",
    "ISFP":"isfp",
    "ENFP":"enfp",
    "INTP":"intp",
    "ESTP":"estp",
    "INFP":"infp",
}
var chara_group = {
    "ESTJ":{matome:"",kan:[]},
    "INFJ":{matome:"",kan:[]},
    "ESFJ":{matome:"",kan:[]},
    "ESFP":{matome:"",kan:[]},
    "ENTJ":{matome:"",kan:[]},
    "ISFJ":{matome:"",kan:[]},
    "ENFJ":{matome:"",kan:[]},
    "INTJ":{matome:"",kan:[]},
    "ISTJ":{matome:"",kan:[]},
    "ISTP":{matome:"",kan:[]},
    "ENTP":{matome:"",kan:[]},
    "ISFP":{matome:"",kan:[]},
    "ENFP":{matome:"",kan:[]},
    "INTP":{matome:"",kan:[]},
    "ESTP":{matome:"",kan:[]},
    "INFP":{matome:"",kan:[]},
}
var kansen_nouryoku = [];
var kansen_namelist = {};
var datatext = ["text01","text02","text03","text04","text05","text06","text07","text08","text09","text10","text11","text12","text13","text14","text15","text16",];
var shareUrl = "";
var tweetset = "";
function shuffle(array){
    for(let i = array.length-1;i>0;i--) {
        let j = Math.floor(Math.random()*(i+1)); // 0 から i のランダムなインデックス
        [array[i],array[j]] = [array[j],array[i]]; // 要素を入れ替えます
    }
}
window.addEventListener('DOMContentLoaded', function() {
    for(var i=0;i<kan_profile.length; i++){
        var inputstatus_deta = {
            陣営:kan_profile[i][0],
            艦種:kan_profile[i][1],
            正規名:kan_profile[i][2],
            レア:kan_profile[i][3],
            装甲:kan_list[i][66],
            耐久:"",
            装填:"",
            回避:"",
            命中:"",
            火力:"",
            雷装:"",
            航空:"",
            対空:"",
            対潜:"",
            速力:"",
            幸運:"",
            潜航:kan_list[i][78]*1,
            消費:kan_list[i][77]*1,
            主砲装備:kan_list[i][67],
            主砲補正:kan_list[i][70],
            主砲砲座:kan_list[i][73],
            副砲装備:kan_list[i][68],
            副砲補正:kan_list[i][71],
            副砲砲座:kan_list[i][74],
            対空装備:kan_list[i][69],
            対空補正:kan_list[i][72],
            対空砲座:kan_list[i][75],
            硬直:kan_list[i][76],
            設備:'設備',
            スキル:kan_profile[i][11],
            記事:kan_profile[i][12],
            声優:kan_profile[i][8],
            声優名:(kan_profile[i][8].indexOf('</a>')) ? (kan_profile[i][8].replace('</a>','').slice(kan_profile[i][8].indexOf('>')+1)):kan_profile[i][8],
            絵師:kan_profile[i][9],
            絵師名:(kan_profile[i][9].indexOf('</a>')) ? (kan_profile[i][9].replace('</a>','').slice(kan_profile[i][9].indexOf('>')+1)):kan_profile[i][9],
            入手:kan_profile[i][4],
            実装日:kan_profile[i][5],
            改造日:kan_profile[i][6],
            進水日:kan_profile[i][7],
            起工日:kan_profile[i][13],
            竣工日:kan_profile[i][14],
            艦級:kan_profile[i][15],
            除外:kan_profile[i][16],
            サブ分類:kan_profile[i][17],
            評価:kan_profile[i][18],
            建造:kan_profile[i][19],
            突破:kan_profile[i][20],
            表記:kan_profile[i][21],
            接頭辞:kan_profile[i][22],
            リンク:kan_profile[i][23],
            番号:kan_profile[i][24],
            wpurl:kan_profile[i][25],
            blogurl:('https://pasokau.com/'+kan_profile[i][25]),
            iconurl:('<a href="https://pasokau.com/'+kan_profile[i][25]+'" target="_blank" ><img src="https://pasokau.com/wp-content/uploads/face/'+kan_profile[i][2]+'.jpg">'+kan_profile[i][2]+'</a>'),
            iconurlmini:('<a href="https://pasokau.com/'+kan_profile[i][25]+'" target="_blank" style="display: flex;align-items: center;text-decoration: none;height: 40px;font-size: 12px;"><img width="40px" src="https://pasokau.com/wp-content/uploads/face/'+kan_profile[i][2]+'.jpg">'),
            ソート:i,
        };
        kansen_nouryoku.push(inputstatus_deta);
        kansen_namelist[kansen_nouryoku[i]['正規名']]=kansen_nouryoku[i];
    }

    for(var i=0;i<datatext.length;i++){
        if(document.querySelectorAll("[data-"+datatext[i]+"]")[0]){
            tage = document.querySelectorAll("[data-"+datatext[i]+"]")[0].dataset[datatext[i]];
            for(var z=0;z<az_matome.length;z++){
                if(az_matome[z][0] == tage){
                    chara_group[tage]['kan'].push(kansen_namelist[az_matome[z][1]]['正規名']);
                    var kanname = (az_matome[z][2] != "") ? az_matome[z][2] : az_matome[z][1];
                    chara_group[tage]['matome'] += ("<div style='width:110px;height: 40px;overflow: hidden;'>"+kansen_namelist[az_matome[z][1]]['iconurlmini']+kanname+"</a></div>");
                }
            }
            document.querySelectorAll("[data-"+datatext[i]+"]")[0].textContent = "";
            document.querySelectorAll("[data-"+datatext[i]+"]")[0].insertAdjacentHTML("afterbegin",chara_group[tage]['matome']);
            document.querySelectorAll("[data-"+datatext[i]+"]")[0].insertAdjacentHTML("beforebegin",'<h4>'+tage+'タイプのキャラ</h4>');
            if(datatext[i] != 'text01'){
                document.querySelectorAll("[data-"+datatext[i]+"]")[0].insertAdjacentHTML("afterend",'<p>⇒<a href="https://pasokau.com/character_'+chara_end[tage]+'" target="_blank">'+tage+'の診断結果を見る</a></p>');
            }
        }
    }

    shareUrl = ("https://pasokau.com/character_"+document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]);
    shuffle(chara_group[document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]]['kan']);
    tweetset = (`【#アズレン性格診断】\n`+
    `あなたの性格は「${document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]}」タイプです！\n\n`+
    `★あなたと似ている艦船\n`+
    `・${chara_group[document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]]['kan'][0]}\n`+
    `・${chara_group[document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]]['kan'][1]}\n`+
    `・${chara_group[document.querySelectorAll("[data-text01]")[0].dataset[datatext[0]]]['kan'][2]}\n`+
    `…などがいます！\n\n`)
});
window.addEventListener('load', function() {
    // twttrが使えるようになったらシェアボタンを作る。
    twttr.widgets.createShareButton(
        shareUrl,
        document.getElementById("tweet10"),{
            count: 'none',
            text: tweetset,
            size: "large",
            hashtags: "",
        }
    );
});
var js, fjs = document.getElementsByTagName('script')[0];
if (!document.getElementById('twitter-wjs')) {
    js = document.createElement('script');
    js.id = 'twitter-wjs';
    js.src = 'https://platform.twitter.com/widgets.js';
    fjs.parentNode.insertBefore(js, fjs);
}
var kingdeta = function(jin){
    switch(jin){
        case "ユニオン":
            return "Eagle_Union";
        break;
        case "ロイヤル":
            return "Royal_Navy";
        break;
        case "重桜":
            return "Sakura_Empire";
        break;
        case "鉄血":
            return "Iron_Blood";
        break;
        case "アイリス":
            return "Iris_Libre";
        break;
        case "ヴィシア":
            return "Vichya_Dominion";
        break;
        case "サディア":
            return "Sardegna_Empire";
        break;
        case "テンペスタ":
            return "Tempesta";
        break;
        case "東煌":
            return "Dragon_Empery";
        break;
        case "北方連合":
            return "Northern_Parliament";
        break;
        case "チュリッパ":
            return "Kingdom_of_Tulipa";
        break;
        case "META":
            return "Universal";
        break;
        case "その他":
            return "Universal";
        break;
        case "BILIBILI":
            return "Collab_Nations";
        break;
        default:
            return "Collab_Nations";
        break;
    }
}
